Fix build failure in tensorflow-lite recipe due to incorrect SRCREV(#47)
tensorflow-lite recipe is failing to
build as the commit hash in the recipe
is not on the branch that is used by
the recipe. Previously we were using
AUTOREV so it was just pulling
HEAD.

ERROR: tensorflow-lite-2.13.1-r0 do_fetch: Fetcher failure:
Unable to find revision 5d37bd0350f0144632629c1aa2ebaef6ca76300b
in branch github.com/r2.13 even from upstream
ERROR: tensorflow-lite-2.13.1-r0 do_fetch:
Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://git.codelinaro.org/clo/le/external/github.com/tensorflow/tensorflow.git;protocol=https;branch=github.com/r2.13')